// app/pages/dashboard/products/[id]/edit.vue
<script setup lang="ts">
import { ArrowLeft, Loader2, Sparkles, UploadCloud, Wand2, X } from "lucide-vue-next"
import { aiService, categoryService, productService } from "~/services/api.service"

definePageMeta({
  layout: "dashboard",
  middleware: "auth" as never,
})

const router = useRouter()
const route = useRoute()
const productId = computed(() => route.params.id as string)

const loading = ref(false)
const fetchingData = ref(true)
const generatingAi = ref(false)
const error = ref("")
const globalCats = ref<any[]>([])
const merchantCats = ref<any[]>([])
const title = ref("")
const description = ref("")
const pricePublic = ref("")
const priceFloor = ref("")
const stock = ref("")
const selectedGlobalCatId = ref("")
const selectedMerchantCatId = ref("")
const dynamicAttributes = ref<Record<string, string>>({})
const existingMedia = ref<string[]>([])

const selectedGlobalCat = computed(() =>
  globalCats.value.find((cat) => cat.id === selectedGlobalCatId.value),
)

const fetchData = async () => {
  try {
    const [globals, merchants, product] = await Promise.all([
      categoryService.getGlobal(),
      categoryService.getMine(),
      productService.getById(productId.value),
    ])

    globalCats.value = globals
    merchantCats.value = merchants
    title.value = product.title || ""
    description.value = product.description || ""
    pricePublic.value = String(product.price_public || "")
    priceFloor.value = String(product.price_floor || "")
    stock.value = String(product.stock || "")
    selectedGlobalCatId.value = product.global_category_id || ""
    selectedMerchantCatId.value = product.merchant_category_id || ""
    dynamicAttributes.value = product.attributes || {}
    existingMedia.value = product.media_urls || []
  } catch (caughtError) {
    console.error("Erreur lors du chargement des donnees", caughtError)
    error.value = "Impossible de charger le produit."
  } finally {
    fetchingData.value = false
  }
}

const handleAttributeChange = (name: string, value: string) => {
  dynamicAttributes.value = {
    ...dynamicAttributes.value,
    [name]: value,
  }
}

const removeExistingFile = (url: string) => {
  existingMedia.value = existingMedia.value.filter((media) => media !== url)
}

const generateAiDescription = async () => {
  if (!title.value || !pricePublic.value) {
    window.alert("Veuillez renseigner au moins le titre et le prix.")
    return
  }

  generatingAi.value = true
  try {
    const data = await aiService.generateDescription({
      title: title.value,
      price: pricePublic.value,
      category: selectedGlobalCat.value?.name,
      attributes: dynamicAttributes.value,
    })
    description.value = data.description
  } catch (err: any) {
    window.alert(`Erreur IA : ${err.message}`)
  } finally {
    generatingAi.value = false
  }
}

const handleSubmit = async (event: Event) => {
  event.preventDefault()
  loading.value = true
  error.value = ""

  try {
    await productService.update(productId.value, {
      title: title.value,
      description: description.value,
      price_public: Number.parseInt(pricePublic.value, 10),
      price_floor: Number.parseInt(priceFloor.value, 10),
      stock: Number.parseInt(stock.value, 10),
      global_category_id: selectedGlobalCatId.value,
      merchant_category_id: selectedMerchantCatId.value,
      attributes: dynamicAttributes.value,
      media_urls: existingMedia.value,
    })
    await router.push("/dashboard")
  } catch (err: any) {
    error.value = err.response?.data?.error || err.message
  } finally {
    loading.value = false
  }
}

onMounted(fetchData)
</script>

<template>
  <div
    v-if="fetchingData"
    class="flex h-screen items-center justify-center bg-gray-50/50"
  >
    <Loader2 class="h-12 w-12 animate-spin text-emerald-600" />
  </div>

  <div
    v-else
    class="mx-auto max-w-4xl pb-20"
  >
    <button
      type="button"
      class="group mb-6 flex items-center space-x-2 font-bold text-gray-500 hover:text-gray-900"
      @click="router.back()"
    >
      <div class="rounded-xl bg-white p-2 shadow-sm transition-colors group-hover:bg-gray-100">
        <ArrowLeft :size="20" />
      </div>
      <span>Retour au catalogue</span>
    </button>

    <div class="rounded-[40px] border border-gray-100 bg-white p-10 shadow-sm">
      <div class="mb-10">
        <h1 class="text-3xl font-black tracking-tight text-gray-900">
          Modifier le produit
        </h1>
        <p class="mt-1 font-medium text-gray-500">
          Mettez a jour les informations de votre article.
        </p>
      </div>

      <div
        v-if="error"
        class="mb-8 rounded-2xl border border-red-100 bg-red-50 p-6 text-sm font-bold text-red-600"
      >
        {{ error }}
      </div>

      <form
        class="space-y-10"
        @submit="handleSubmit"
      >
        <div class="rounded-[32px] border border-gray-100 bg-gray-50 p-8">
          <label class="mb-6 block text-xs font-black uppercase tracking-widest text-gray-400">
            Photos du produit
          </label>
          <div class="flex flex-wrap gap-4">
            <div
              v-for="(url, index) in existingMedia"
              :key="url"
              class="group relative h-32 w-32 overflow-hidden rounded-2xl border-4 border-white shadow-md"
            >
              <img
                :src="url"
                class="h-full w-full object-cover"
                alt="Product"
              >
              <button
                type="button"
                class="absolute right-2 top-2 rounded-xl bg-red-500 p-1.5 text-white opacity-0 shadow-lg transition-opacity hover:bg-red-600 group-hover:opacity-100"
                @click="removeExistingFile(url)"
              >
                <X :size="16" />
              </button>
            </div>

            <div
              v-if="existingMedia.length === 0"
              class="flex w-full flex-col items-center justify-center py-10 text-gray-300"
            >
              <UploadCloud :size="48" />
              <p class="mt-2 text-xs font-bold uppercase">
                Aucune image
              </p>
            </div>
          </div>
          <p class="mt-4 text-[10px] font-bold uppercase tracking-tight text-gray-400">
            * Pour changer les images, supprimez l'article et recreez-le.
          </p>
        </div>

        <div class="grid grid-cols-1 gap-8 md:grid-cols-2">
          <div class="md:col-span-2">
            <label class="mb-2 block text-sm font-black text-gray-700">
              Titre du produit *
            </label>
            <input
              v-model="title"
              type="text"
              required
              class="w-full rounded-2xl border-2 border-gray-100 px-6 py-4 font-bold text-gray-800 outline-none transition-all focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10"
            >
          </div>

          <div>
            <label class="mb-2 block text-sm font-black text-gray-700">
              Categorie Globale *
            </label>
            <select
              v-model="selectedGlobalCatId"
              required
              class="w-full appearance-none rounded-2xl border-2 border-gray-100 bg-white px-6 py-4 font-bold text-gray-800 outline-none transition-all focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10"
            >
              <option value="">
                Selectionner...
              </option>
              <option
                v-for="cat in globalCats"
                :key="cat.id"
                :value="cat.id"
              >
                {{ cat.name }}
              </option>
            </select>
          </div>

          <div>
            <label class="mb-2 block text-sm font-black text-gray-700">
              Collection Boutique
            </label>
            <select
              v-model="selectedMerchantCatId"
              class="w-full appearance-none rounded-2xl border-2 border-gray-100 bg-white px-6 py-4 font-bold text-gray-800 outline-none transition-all focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10"
            >
              <option value="">
                Aucune...
              </option>
              <option
                v-for="cat in merchantCats"
                :key="cat.id"
                :value="cat.id"
              >
                {{ cat.name }}
              </option>
            </select>
          </div>

          <div
            v-if="selectedGlobalCat?.fields_config?.length"
            class="space-y-6 rounded-[32px] border-2 border-emerald-50 bg-emerald-50/30 p-8 md:col-span-2"
          >
            <div class="flex items-center gap-3">
              <div class="rounded-xl bg-emerald-500 p-2 text-white">
                <Sparkles :size="18" />
              </div>
              <h3 class="text-sm font-black uppercase tracking-widest text-emerald-800">
                Caracteristiques {{ selectedGlobalCat.name }}
              </h3>
            </div>
            <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
              <div
                v-for="field in selectedGlobalCat.fields_config"
                :key="field.name"
              >
                <label class="mb-2 block text-[10px] font-black uppercase tracking-widest text-emerald-600">
                  {{ field.label }}
                </label>
                <input
                  :type="field.type"
                  :placeholder="field.placeholder"
                  :value="dynamicAttributes[field.name] || ''"
                  class="w-full rounded-xl border-2 border-emerald-100 bg-white/50 px-5 py-3 font-bold text-gray-800 outline-none transition-all focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10"
                  @input="handleAttributeChange(field.name, ($event.target as HTMLInputElement).value)"
                >
              </div>
            </div>
          </div>

          <div class="md:col-span-2">
            <div class="mb-2 flex items-center justify-between">
              <label class="block text-sm font-black text-gray-700">
                Description marketing
              </label>
              <button
                type="button"
                :disabled="generatingAi"
                class="flex items-center gap-2 rounded-xl bg-purple-600 px-4 py-2 text-[10px] font-black uppercase tracking-widest text-white shadow-lg shadow-purple-600/20 transition-all hover:bg-purple-700 active:scale-95 disabled:opacity-50"
                @click="generateAiDescription"
              >
                <Loader2
                  v-if="generatingAi"
                  class="animate-spin"
                  :size="14"
                />
                <Wand2
                  v-else
                  :size="14"
                />
                Generer avec IA
              </button>
            </div>
            <textarea
              v-model="description"
              rows="5"
              class="w-full resize-none rounded-2xl border-2 border-gray-100 px-6 py-4 font-medium text-gray-800 outline-none transition-all focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10"
            />
          </div>

          <div>
            <label class="mb-2 block text-sm font-black text-gray-700">
              Prix public (FCFA) *
            </label>
            <input
              v-model="pricePublic"
              type="number"
              required
              class="w-full rounded-2xl border-2 border-gray-100 px-6 py-4 font-mono text-xl font-black text-gray-800 outline-none transition-all focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10"
            >
          </div>

          <div>
            <label class="mb-2 block text-sm font-black text-gray-700">
              Prix plancher (FCFA) *
            </label>
            <input
              v-model="priceFloor"
              type="number"
              required
              class="w-full rounded-2xl border-2 border-gray-100 px-6 py-4 font-mono text-xl font-black text-gray-800 outline-none transition-all focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10"
            >
          </div>

          <div>
            <label class="mb-2 block text-sm font-black text-gray-700">
              Stock disponible *
            </label>
            <input
              v-model="stock"
              type="number"
              required
              class="w-full rounded-2xl border-2 border-gray-100 px-6 py-4 text-xl font-bold text-gray-800 outline-none transition-all focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10"
            >
          </div>
        </div>

        <div class="flex justify-end border-t border-gray-50 pt-10">
          <button
            type="submit"
            :disabled="loading"
            class="rounded-2xl bg-emerald-600 px-12 py-5 text-lg font-black text-white shadow-2xl shadow-emerald-600/30 transition-all hover:bg-emerald-700 active:scale-95 disabled:opacity-50"
          >
            {{ loading ? "Enregistrement..." : "Appliquer les modifications" }}
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

// src/app/dashboard/products/[id]/edit/page.tsx
"use client";

import { useState, useEffect } from "react";
import { useRouter, useParams } from "next/navigation";
import { ArrowLeft, UploadCloud, X, Loader2, Sparkles, Wand2 } from "lucide-react";
import { productService, categoryService, aiService } from "@/services/api.service";

interface CategoryField {
  name: string;
  label: string;
  type: string;
  placeholder?: string;
  options?: string[];
}

interface GlobalCategory {
  id: string;
  name: string;
  fields_config: CategoryField[];
}

interface MerchantCategory {
  id: string;
  name: string;
}

export default function EditProduct() {
  const router = useRouter();
  const params = useParams();
  const productId = params.id as string;

  const [loading, setLoading] = useState(false);
  const [fetchingData, setFetchingData] = useState(true);
  const [generatingAi, setGeneratingAi] = useState(false);
  const [error, setError] = useState("");
  
  const [globalCats, setGlobalCats] = useState<GlobalCategory[]>([]);
  const [merchantCats, setMerchantCats] = useState<MerchantCategory[]>([]);

  // Form State
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [pricePublic, setPricePublic] = useState("");
  const [priceFloor, setPriceFloor] = useState("");
  const [stock, setStock] = useState("");
  const [selectedGlobalCatId, setSelectedGlobalCatId] = useState("");
  const [selectedMerchantCatId, setSelectedMerchantCatId] = useState("");
  const [dynamicAttributes, setDynamicAttributes] = useState<Record<string, any>>({});
  const [existingMedia, setExistingMedia] = useState<string[]>([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [globals, merchants, product] = await Promise.all([
          categoryService.getGlobal(),
          categoryService.getMine(),
          productService.getById(productId)
        ]);

        setGlobalCats(globals);
        setMerchantCats(merchants);
        
        if (product) {
          setTitle(product.title);
          setDescription(product.description || "");
          setPricePublic(product.price_public.toString());
          setPriceFloor(product.price_floor.toString());
          setStock(product.stock.toString());
          setSelectedGlobalCatId(product.global_category_id || "");
          setSelectedMerchantCatId(product.merchant_category_id || "");
          setDynamicAttributes(product.attributes || {});
          setExistingMedia(product.media_urls || []);
        }
      } catch (err) {
        console.error("Erreur lors du chargement des données", err);
        setError("Impossible de charger le produit.");
      } finally {
        setFetchingData(false);
      }
    };

    fetchData();
  }, [productId]);

  const selectedGlobalCat = globalCats.find(c => c.id === selectedGlobalCatId);

  const handleAttributeChange = (name: string, value: any) => {
    setDynamicAttributes(prev => ({ ...prev, [name]: value }));
  };

  const removeExistingFile = (url: string) => {
    setExistingMedia(existingMedia.filter(m => m !== url));
  };

  const generateAiDescription = async () => {
    if (!title || !pricePublic) {
      alert("Veuillez renseigner au moins le titre et le prix.");
      return;
    }

    setGeneratingAi(true);
    try {
      const data = await aiService.generateDescription({
        title,
        price: pricePublic,
        category: selectedGlobalCat?.name,
        attributes: dynamicAttributes
      });
      setDescription(data.description);
    } catch (err: any) {
      alert("Erreur IA : " + err.message);
    } finally {
      setGeneratingAi(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    const updateData = {
      title,
      description,
      price_public: parseInt(pricePublic, 10),
      price_floor: parseInt(priceFloor, 10),
      stock: parseInt(stock, 10),
      global_category_id: selectedGlobalCatId,
      merchant_category_id: selectedMerchantCatId,
      attributes: dynamicAttributes,
      media_urls: existingMedia
    };

    try {
      await productService.update(productId, updateData);
      router.push("/dashboard");
    } catch (err: any) {
      setError(err.response?.data?.error || err.message);
    } finally {
      setLoading(false);
    }
  };

  if (fetchingData) return <div className="flex h-screen items-center justify-center bg-gray-50/50"><Loader2 className="animate-spin text-emerald-600 h-12 w-12" /></div>;

  return (
    <div className="max-w-4xl mx-auto pb-20">
      <button 
        onClick={() => router.back()}
        className="flex items-center space-x-2 text-gray-500 hover:text-gray-900 mb-6 font-bold group"
      >
        <div className="p-2 bg-white rounded-xl shadow-sm group-hover:bg-gray-100 transition-colors">
          <ArrowLeft size={20} />
        </div>
        <span>Retour au catalogue</span>
      </button>

      <div className="bg-white rounded-[40px] shadow-sm border border-gray-100 p-10">
        <div className="mb-10">
          <h1 className="text-3xl font-black text-gray-900 tracking-tight">Modifier le produit</h1>
          <p className="text-gray-500 font-medium mt-1">Mettez à jour les informations de votre article.</p>
        </div>

        {error && <div className="mb-8 rounded-2xl bg-red-50 p-6 text-sm text-red-600 border border-red-100 font-bold">{error}</div>}

        <form onSubmit={handleSubmit} className="space-y-10">
          {/* Media Section */}
          <div className="bg-gray-50 p-8 rounded-[32px] border border-gray-100">
            <label className="block text-xs font-black text-gray-400 mb-6 uppercase tracking-widest">Photos du produit</label>
            <div className="flex flex-wrap gap-4">
              {existingMedia.map((url, idx) => (
                <div key={idx} className="relative w-32 h-32 rounded-2xl overflow-hidden border-4 border-white shadow-md group">
                  <img src={url} className="w-full h-full object-cover" alt="Product" />
                  <button type="button" onClick={() => removeExistingFile(url)} className="absolute top-2 right-2 bg-red-500 text-white rounded-xl p-1.5 hover:bg-red-600 shadow-lg opacity-0 group-hover:opacity-100 transition-opacity">
                    <X size={16} />
                  </button>
                </div>
              ))}
              {existingMedia.length === 0 && (
                <div className="w-full py-10 flex flex-col items-center justify-center text-gray-300">
                  <UploadCloud size={48} />
                  <p className="text-xs font-bold mt-2 uppercase">Aucune image</p>
                </div>
              )}
            </div>
            <p className="text-[10px] text-gray-400 mt-4 font-bold uppercase tracking-tight">* Pour changer les images, supprimez l'article et recréez-le (amélioration à venir).</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="md:col-span-2">
              <label className="block text-sm font-black text-gray-700 mb-2">Titre du produit *</label>
              <input type="text" required value={title} onChange={e => setTitle(e.target.value)} className="w-full rounded-2xl border-2 border-gray-100 px-6 py-4 focus:ring-4 focus:ring-emerald-500/10 focus:border-emerald-500 outline-none text-gray-800 font-bold transition-all" />
            </div>

            <div>
              <label className="block text-sm font-black text-gray-700 mb-2">Catégorie Globale *</label>
              <select 
                required 
                value={selectedGlobalCatId} 
                onChange={e => setSelectedGlobalCatId(e.target.value)}
                className="w-full rounded-2xl border-2 border-gray-100 px-6 py-4 focus:ring-4 focus:ring-emerald-500/10 focus:border-emerald-500 outline-none text-gray-800 font-bold transition-all appearance-none bg-white"
              >
                <option value="">Sélectionner...</option>
                {globalCats.map(cat => (
                  <option key={cat.id} value={cat.id}>{cat.name}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-black text-gray-700 mb-2">Collection Boutique</label>
              <select 
                value={selectedMerchantCatId} 
                onChange={e => setSelectedMerchantCatId(e.target.value)}
                className="w-full rounded-2xl border-2 border-gray-100 px-6 py-4 focus:ring-4 focus:ring-emerald-500/10 focus:border-emerald-500 outline-none text-gray-800 font-bold transition-all appearance-none bg-white"
              >
                <option value="">Aucune...</option>
                {merchantCats.map(cat => (
                  <option key={cat.id} value={cat.id}>{cat.name}</option>
                ))}
              </select>
            </div>

            {selectedGlobalCat && selectedGlobalCat.fields_config.length > 0 && (
              <div className="md:col-span-2 bg-emerald-50/30 p-8 rounded-[32px] border-2 border-emerald-50 space-y-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-emerald-500 rounded-xl text-white">
                    <Sparkles size={18} />
                  </div>
                  <h3 className="text-sm font-black text-emerald-800 uppercase tracking-widest">Caractéristiques {selectedGlobalCat.name}</h3>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {selectedGlobalCat.fields_config.map(field => (
                    <div key={field.name}>
                      <label className="block text-[10px] font-black text-emerald-600 mb-2 uppercase tracking-widest">{field.label}</label>
                      <input 
                        type={field.type} 
                        placeholder={field.placeholder}
                        value={dynamicAttributes[field.name] || ""}
                        onChange={e => handleAttributeChange(field.name, e.target.value)}
                        className="w-full rounded-xl border-2 border-emerald-100 px-5 py-3 focus:ring-4 focus:ring-emerald-500/10 focus:border-emerald-500 outline-none text-gray-800 font-bold transition-all bg-white/50"
                      />
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="md:col-span-2">
              <div className="flex items-center justify-between mb-2">
                <label className="block text-sm font-black text-gray-700">Description marketing</label>
                <button 
                  type="button"
                  onClick={generateAiDescription}
                  disabled={generatingAi}
                  className="flex items-center gap-2 text-[10px] font-black bg-purple-600 text-white px-4 py-2 rounded-xl hover:bg-purple-700 transition-all shadow-lg shadow-purple-600/20 disabled:opacity-50 active:scale-95 uppercase tracking-widest"
                >
                  {generatingAi ? <Loader2 className="animate-spin" size={14} /> : <Wand2 size={14} />}
                  Générer avec IA ✨
                </button>
              </div>
              <textarea 
                value={description}
                onChange={e => setDescription(e.target.value)}
                rows={5}
                className="w-full rounded-2xl border-2 border-gray-100 px-6 py-4 focus:ring-4 focus:ring-emerald-500/10 focus:border-emerald-500 outline-none text-gray-800 font-medium transition-all resize-none"
              />
            </div>

            <div>
              <label className="block text-sm font-black text-gray-700 mb-2">Prix public (FCFA) *</label>
              <input type="number" required value={pricePublic} onChange={e => setPricePublic(e.target.value)} className="w-full rounded-2xl border-2 border-gray-100 px-6 py-4 focus:ring-4 focus:ring-emerald-500/10 focus:border-emerald-500 outline-none text-gray-800 font-mono text-xl font-black transition-all" />
            </div>

            <div>
              <label className="block text-sm font-black text-gray-700 mb-2">Stock disponible *</label>
              <input type="number" required value={stock} onChange={e => setStock(e.target.value)} className="w-full rounded-2xl border-2 border-gray-100 px-6 py-4 focus:ring-4 focus:ring-emerald-500/10 focus:border-emerald-500 outline-none text-gray-800 font-bold text-xl transition-all" />
            </div>
          </div>

          <div className="pt-10 border-t border-gray-50 flex justify-end">
            <button 
              type="submit" 
              disabled={loading} 
              className="bg-emerald-600 hover:bg-emerald-700 text-white px-12 py-5 rounded-2xl font-black text-lg transition-all shadow-2xl shadow-emerald-600/30 active:scale-95 disabled:opacity-50"
            >
              {loading ? "Enregistrement..." : "Appliquer les modifications"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
