// app/layouts/dashboard.vue
<script setup lang="ts">
import {
  ChevronRight,
  LayoutDashboard,
  Loader2,
  LogOut,
  Megaphone,
  Package,
  Store,
  Tag,
  User,
  Zap,
} from "lucide-vue-next"
import { shopService, userService } from "~/services/api.service"

const route = useRoute()
const router = useRouter()

const loading = ref(true)
const showProfileModal = ref(false)

const isSetupRoute = computed(() => route.path.includes("/setup"))

const navItems = computed(() => [
  {
    name: "Catalogue",
    icon: Package,
    path: "/dashboard",
    active: route.path === "/dashboard" || route.path.includes("/products"),
  },
  {
    name: "Promotions",
    icon: Zap,
    path: "/dashboard/promotions",
    active: route.path.includes("/promotions"),
  },
  {
    name: "Categories",
    icon: Tag,
    path: "/dashboard/categories",
    active: route.path.includes("/categories"),
  },
  {
    name: "Ma Boutique",
    icon: Store,
    path: "/dashboard/settings",
    active: route.path.includes("/settings"),
  },
  {
    name: "Mon Profil",
    icon: User,
    path: "/dashboard/profile",
    active: route.path.includes("/profile"),
  },
])

const runDashboardGuard = async () => {
  loading.value = true

  const token = localStorage.getItem("wazashop_token")
  if (!token) {
    await navigateTo("/")
    loading.value = false
    return
  }

  try {
    const [shopData, userData] = await Promise.all([
      shopService.getMine().catch(() => null),
      userService.getMe().catch(() => null),
    ])

    if (!shopData && !route.path.includes("/setup")) {
      await navigateTo("/dashboard/setup")
      return
    }

    if (
      userData &&
      (!userData.firstName || !userData.lastName) &&
      !route.path.includes("/setup") &&
      !route.path.includes("/profile")
    ) {
      const lastDismissedStr = localStorage.getItem("wazashop_profile_modal_dismissed_at")
      const lastDismissed = lastDismissedStr ? Number.parseInt(lastDismissedStr, 10) : 0
      const oneHourMs = 60 * 60 * 1000

      showProfileModal.value = Date.now() - lastDismissed > oneHourMs
    } else {
      showProfileModal.value = false
    }
  } catch (error) {
    console.error(error)
    await navigateTo("/")
  } finally {
    loading.value = false
  }
}

const handleLogout = async () => {
  localStorage.removeItem("wazashop_token")
  await navigateTo("/")
}

const goToProfile = async () => {
  showProfileModal.value = false
  await navigateTo("/dashboard/profile")
}

const dismissProfileReminder = () => {
  localStorage.setItem("wazashop_profile_modal_dismissed_at", Date.now().toString())
  showProfileModal.value = false
}

onMounted(runDashboardGuard)
watch(() => route.path, runDashboardGuard)
</script>

<template>
  <div
    v-if="loading"
    class="flex min-h-screen items-center justify-center bg-[#fdfdfd]"
  >
    <Loader2 class="h-10 w-10 animate-spin text-emerald-600" />
  </div>

  <slot v-else-if="isSetupRoute" />

  <div
    v-else
    class="flex min-h-screen bg-[#f8f9fa] text-gray-900 font-sans"
  >
    <aside class="relative z-20 hidden w-72 flex-col border-r border-gray-100 bg-white shadow-2xl shadow-gray-200/50 lg:flex">
      <div class="p-10 pb-12">
        <div class="flex items-center gap-3">
          <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-600 text-white shadow-lg shadow-emerald-600/20">
            <LayoutDashboard :size="20" />
          </div>
          <h1 class="text-2xl font-black tracking-tighter text-gray-900">
            WazaShop
          </h1>
        </div>
      </div>

      <nav class="flex-1 space-y-2 px-6">
        <div class="mb-4 px-4">
          <p class="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400">
            Menu Principal
          </p>
        </div>

        <NuxtLink
          v-for="item in navItems"
          :key="item.name"
          :to="item.path"
          class="group flex items-center justify-between rounded-2xl px-4 py-4 font-bold transition-all duration-300"
          :class="item.active ? 'translate-x-2 bg-emerald-600 text-white shadow-xl shadow-emerald-600/20' : 'text-gray-500 hover:bg-gray-50 hover:text-gray-900'"
        >
          <div class="flex items-center gap-4">
            <component
              :is="item.icon"
              :size="22"
              :class="item.active ? 'text-white' : 'text-gray-400 transition-colors group-hover:text-emerald-600'"
            />
            <span>{{ item.name }}</span>
          </div>
          <ChevronRight
            v-if="item.active"
            :size="16"
          />
        </NuxtLink>

        <div class="mb-4 px-4 pt-10">
          <p class="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400">
            Outils Marketing
          </p>
        </div>

        <NuxtLink
          to="/dashboard/marketing"
          class="group relative flex items-center justify-between overflow-hidden rounded-2xl px-4 py-4 font-bold transition-all duration-300"
          :class="route.path.includes('/marketing') ? 'translate-x-2 bg-amber-500 text-white shadow-xl shadow-amber-500/20' : 'text-gray-500 hover:bg-gray-50 hover:text-gray-900'"
        >
          <div class="flex items-center gap-4">
            <Megaphone
              :size="22"
              :class="route.path.includes('/marketing') ? 'text-white' : 'text-amber-500'"
            />
            <span>Booster de Ventes</span>
          </div>
          <span
            class="rounded-full px-2 py-0.5 text-[8px] font-black uppercase tracking-widest"
            :class="route.path.includes('/marketing') ? 'bg-white/20' : 'bg-amber-100 text-amber-600'"
          >
            New
          </span>
        </NuxtLink>
      </nav>

      <div class="border-t border-gray-50 p-6">
        <button
          class="group flex w-full items-center gap-4 rounded-2xl px-4 py-4 font-black text-gray-400 transition-all hover:bg-red-50 hover:text-red-500"
          type="button"
          @click="handleLogout"
        >
          <LogOut
            :size="22"
            class="transition-transform group-hover:rotate-12"
          />
          <span>Deconnexion</span>
        </button>
      </div>
    </aside>

    <main class="flex-1 overflow-y-auto">
      <div class="mx-auto max-w-[1600px] p-6 md:p-12">
        <slot />
      </div>
    </main>

    <div
      v-if="showProfileModal"
      class="fixed inset-0 z-[100] flex items-center justify-center bg-gray-900/40 p-6 backdrop-blur-md"
    >
      <div class="relative w-full max-w-md overflow-hidden rounded-[48px] bg-white p-12 shadow-2xl">
        <div class="absolute right-0 top-0 -mr-16 -mt-16 h-32 w-32 rounded-full bg-emerald-50" />

        <div class="relative text-center">
          <div class="mx-auto mb-8 flex h-24 w-24 rotate-6 items-center justify-center rounded-[32px] bg-emerald-600 text-white shadow-2xl shadow-emerald-600/30">
            <User :size="48" />
          </div>
          <h2 class="text-3xl font-black leading-tight text-gray-900">
            Profil incomplet
          </h2>
          <p class="mt-4 text-lg font-medium leading-relaxed text-gray-500">
            Prenez une minute pour ajouter votre nom. Un profil complet inspire
            <span class="font-black text-emerald-600"> 10x plus confiance </span>
            a vos clients WhatsApp.
          </p>
        </div>

        <div class="mt-10 flex flex-col gap-4">
          <button
            class="w-full rounded-3xl bg-emerald-600 px-8 py-5 text-lg font-black text-white shadow-xl shadow-emerald-600/20 transition-all hover:scale-105 hover:bg-emerald-700 active:scale-95"
            type="button"
            @click="goToProfile"
          >
            Completer mon profil
          </button>
          <button
            class="w-full rounded-3xl bg-gray-50 px-8 py-5 font-black text-gray-400 transition-all hover:bg-gray-100 hover:text-gray-600"
            type="button"
            @click="dismissProfileReminder"
          >
            Peut-etre plus tard
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// src/app/dashboard/page.tsx
"use client";

import { useEffect, useState } from "react";
import { Plus, Package, Image as ImageIcon, Search, Filter, Edit2, Trash2, Tag, AlertTriangle } from "lucide-react";
import { useRouter } from "next/navigation";
import { productService, categoryService } from "@/services/api.service";

export default function Dashboard() {
  const [products, setProducts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedGlobalCat, setSelectedGlobalCat] = useState("all");
  const [globalCats, setGlobalCats] = useState<any[]>([]);
  
  const router = useRouter();

  const fetchData = async () => {
    try {
      const [productsData, categoriesData] = await Promise.all([
        productService.getAll(),
        categoryService.getGlobal()
      ]);
      setProducts(productsData);
      setGlobalCats(categoriesData);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  const handleDelete = async (id: string) => {
    if (!confirm("Voulez-vous vraiment supprimer ce produit ?")) return;

    try {
      await productService.delete(id);
      setProducts(products.filter(p => p.id !== id));
    } catch (err) {
      console.error(err);
    }
  };

  const filteredProducts = products.filter(p => {
    const matchesSearch = p.title.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCat = selectedGlobalCat === "all" || p.global_category_id === selectedGlobalCat;
    return matchesSearch && matchesCat;
  });

  const getStockStatus = (stock: number) => {
    if (stock <= 0) return { label: "Rupture", color: "bg-red-100 text-red-700 border-red-200" };
    if (stock <= 5) return { label: "Stock faible", color: "bg-orange-100 text-orange-700 border-orange-200" };
    return { label: "En stock", color: "bg-emerald-100 text-emerald-700 border-emerald-200" };
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-black text-gray-900 tracking-tight">Mon Catalogue</h1>
          <p className="text-gray-500 font-medium">Gérez vos articles et optimisez vos stocks.</p>
        </div>
        <button 
          onClick={() => router.push("/dashboard/products/new")}
          className="flex items-center justify-center space-x-2 bg-emerald-600 hover:bg-emerald-700 text-white px-6 py-3 rounded-2xl font-bold transition-all shadow-lg shadow-emerald-600/20 active:scale-95"
        >
          <Plus size={20} />
          <span>Ajouter un produit</span>
        </button>
      </div>

      {/* Filters & Search */}
      <div className="bg-white p-4 rounded-3xl shadow-sm border border-gray-100 flex flex-col md:flex-row gap-4">
        <div className="relative flex-1">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
          <input 
            type="text" 
            placeholder="Rechercher un produit..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-gray-50 border-none rounded-2xl pl-12 pr-4 py-3 focus:ring-2 focus:ring-emerald-500/20 outline-none transition-all text-gray-700 font-medium"
          />
        </div>
        <div className="flex items-center gap-2 overflow-x-auto pb-2 md:pb-0 scrollbar-hide">
          <Filter className="text-gray-400 mr-2 shrink-0" size={20} />
          <button 
            onClick={() => setSelectedGlobalCat("all")}
            className={`px-4 py-2 rounded-xl text-sm font-bold whitespace-nowrap transition-all ${selectedGlobalCat === "all" ? 'bg-emerald-600 text-white shadow-md' : 'bg-gray-50 text-gray-600 hover:bg-gray-100'}`}
          >
            Tous
          </button>
          {globalCats.map(cat => (
            <button 
              key={cat.id}
              onClick={() => setSelectedGlobalCat(cat.id)}
              className={`px-4 py-2 rounded-xl text-sm font-bold whitespace-nowrap transition-all ${selectedGlobalCat === cat.id ? 'bg-emerald-600 text-white shadow-md' : 'bg-gray-50 text-gray-600 hover:bg-gray-100'}`}
            >
              {cat.name}
            </button>
          ))}
        </div>
      </div>

      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {[1,2,3,4].map(i => (
            <div key={i} className="bg-white rounded-3xl h-80 animate-pulse border border-gray-100"></div>
          ))}
        </div>
      ) : filteredProducts.length === 0 ? (
        <div className="bg-white rounded-[40px] border-2 border-dashed border-gray-200 p-20 text-center flex flex-col items-center">
          <div className="bg-emerald-50 p-6 rounded-full mb-6">
            <Package className="h-12 w-12 text-emerald-600" />
          </div>
          <h3 className="text-2xl font-black text-gray-900 mb-2">Aucun produit trouvé</h3>
          <p className="text-gray-500 mb-8 max-w-sm font-medium">
            {searchTerm || selectedGlobalCat !== "all" ? "Ajustez vos filtres pour trouver ce que vous cherchez." : "Commencez par ajouter votre premier produit pour lancer votre boutique !"}
          </p>
          {!searchTerm && selectedGlobalCat === "all" && (
            <button 
              onClick={() => router.push("/dashboard/products/new")}
              className="bg-emerald-600 text-white px-8 py-4 rounded-2xl font-bold shadow-xl shadow-emerald-600/20 hover:scale-105 transition-all"
            >
              + Ajouter mon premier produit
            </button>
          )}
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {filteredProducts.map(product => {
            const status = getStockStatus(product.stock);
            return (
              <div key={product.id} className="group bg-white rounded-[32px] shadow-sm border border-gray-100 overflow-hidden hover:shadow-2xl hover:shadow-emerald-900/5 transition-all duration-300 flex flex-col">
                {/* Image Section */}
                <div className="h-56 bg-gray-50 relative overflow-hidden">
                  {product.media_urls && product.media_urls.length > 0 ? (
                    <img src={product.media_urls[0]} alt={product.title} className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" />
                  ) : (
                    <div className="w-full h-full flex items-center justify-center bg-gray-50">
                      <ImageIcon className="h-12 w-12 text-gray-200" />
                    </div>
                  )}
                  
                  {/* Category Badge */}
                  {product.globalCategory && (
                    <div className="absolute top-4 left-4 bg-white/90 backdrop-blur-sm px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-wider text-gray-700 shadow-sm">
                      {product.globalCategory.name}
                    </div>
                  )}

                  {/* Quick Actions Overlay */}
                  <div className="absolute top-4 right-4 flex flex-col gap-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button 
                      onClick={() => router.push(`/dashboard/products/${product.id}/edit`)}
                      className="p-3 bg-white text-gray-700 rounded-2xl shadow-xl hover:bg-emerald-600 hover:text-white transition-all"
                    >
                      <Edit2 size={18} />
                    </button>
                    <button 
                      onClick={() => handleDelete(product.id)}
                      className="p-3 bg-white text-gray-700 rounded-2xl shadow-xl hover:bg-red-600 hover:text-white transition-all"
                    >
                      <Trash2 size={18} />
                    </button>
                  </div>
                </div>

                {/* Content Section */}
                <div className="p-6 flex-1 flex flex-col">
                  <div className="flex-1">
                    <h3 className="font-bold text-gray-900 text-lg line-clamp-2 leading-tight mb-2 group-hover:text-emerald-600 transition-colors">{product.title}</h3>
                    
                    <div className="flex items-center gap-2 mb-4">
                      <div className={`px-3 py-1 rounded-full text-[10px] font-bold border ${status.color}`}>
                        {status.label}: {product.stock}
                      </div>
                      {product.stock <= 5 && product.stock > 0 && <AlertTriangle size={14} className="text-orange-500" />}
                    </div>
                  </div>

                  <div className="pt-4 border-t border-gray-50 flex justify-between items-center">
                    <div className="flex flex-col">
                      <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Prix</span>
                      <span className="text-xl font-black text-gray-900">{product.price_public.toLocaleString()} <span className="text-xs">F</span></span>
                    </div>
                    {product.merchantCategory && (
                      <div className="flex items-center gap-1 text-gray-400 bg-gray-50 px-2 py-1 rounded-lg">
                        <Tag size={12} />
                        <span className="text-[10px] font-bold truncate max-w-[80px]">{product.merchantCategory.name}</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
